FROM node:lts-alpine

# copy all files (including .git) and set the dest as working dir
ADD . /usr/app/diaryofapolymath
WORKDIR /usr/app/diaryofapolymath

RUN apk update \
    && apk add git

RUN npm install -g \
    semantic-release \
    @semantic-release/changelog \
    @semantic-release/git \
    @semantic-release/exec

ENTRYPOINT ["./run", "start:release"]
