FROM node:lts-alpine

# copy all files and set the dest as working dir
COPY . /usr/home/diaryofapolymath
WORKDIR /usr/home/diaryofapolymath

RUN apk update \
    && apk add git

RUN npm install -g \
    semantic-release \
    @semantic-release/changelog \
    @semantic-release/git \
    @semantic-release/exec

ENTRYPOINT ["./run", "start:release"]
