FROM nikolaik/python-nodejs:python3.9-nodejs16-slim

ENV PYTHONUNBUFFERED 1

# copy all files and set the dest as working dir
COPY . /usr/app/diaryofapolymath
WORKDIR /usr/app/diaryofapolymath

# setup python environment
RUN set -a && . ./.env && set +a \
    && pip install pipenv \
    && pipenv requirements --dev > requirements.txt \
    && pip3 install -r requirements.txt --no-cache-dir \
    && pip3 uninstall pipenv -y \
    && rm -rf Pipfile*

ENTRYPOINT ["./run", "start:test"]
