# Generated by Django 4.1.7 on 2023-04-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image_title", models.CharField(max_length=25)),
                ("image_alt", models.CharField(max_length=50)),
                ("image_src_url", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now_add=True)),
                ("header", models.CharField(max_length=120, unique=True)),
                ("body", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="about.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon_title", models.CharField(max_length=25)),
                ("icon_alt", models.CharField(max_length=50)),
                ("icon_href", models.CharField(max_length=250)),
                ("icon_src_url", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="about.profile"
                    ),
                ),
            ],
        ),
    ]
