# Generated by Django 4.2.7 on 2023-11-25 16:49

import os

from django.db import migrations


class Migration(migrations.Migration):
    def generate_superuser(apps, schema_editor):
        from about.models import Profile as User

        User.objects.create_superuser(
            username=os.environ.get("DJANGO_SUPERUSER_NAME"),
            email=os.environ.get("DJANGO_SUPERUSER_EMAIL"),
            password=os.environ.get("DJANGO_SUPERUSER_PASSWORD"),
        ).save()

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [migrations.RunPython(generate_superuser)]
