# Generated by Django 4.2.7 on 2023-11-25 16:49

import os

from django.db import migrations


class Migration(migrations.Migration):
    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SUPERUSER_NAME = os.environ.get("DJANGO_SUPERUSER_NAME")
        DJANGO_SUPERUSER_EMAIL = os.environ.get("DJANGO_SUPERUSER_EMAIL")
        DJANGO_SUPERUSER_PASSWORD = os.environ.get("DJANGO_SUPERUSER_PASSWORD")

        superuser = User.objects.create_superuser(
            username=DJANGO_SUPERUSER_NAME,
            email=DJANGO_SUPERUSER_EMAIL,
            password=DJANGO_SUPERUSER_PASSWORD,
        )

        superuser.save()

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [migrations.RunPython(generate_superuser)]
