# Generated by Django 4.2.2 on 2023-07-02 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["icon_title"]},
        ),
        migrations.AlterModelOptions(
            name="timeline",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
        migrations.AddField(
            model_name="timeline",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timeline",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
