# Generated by Django 4.2.3 on 2023-07-04 10:05

import about.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_alter_link_options_alter_timeline_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[
                ("objects", about.managers.ProfileManager()),
            ],
        ),
    ]
