# Generated by Django 4.2.3 on 2026-03-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_src_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
